apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
        - name: cert-manager
          image: cert-manager:latest
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: certs
              mountPath: /etc/letsencrypt
          env:
            - name: CERT_RENEWAL_INTERVAL
              value: "12h"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: certs
          hostPath:
            path: /path/to/certbot/conf