apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-config
  namespace: cert-manager
data:
  config.yaml: |
    certificate_defaults:
      organization: "Local Development"
      country: "US"
      validity_days: 365
    monitoring:
      enabled: true
      metrics_port: 19090
    logging:
      level: "INFO"
      format: "json"
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'cert-manager'
        static_configs:
          - targets: ['cert-manager-service:19090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
        - name: cert-manager
          image: cert-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 19090
              name: metrics
          volumeMounts:
            - name: cert-manager-config
              mountPath: /app/config
            - name: certs-volume
              mountPath: /etc/ssl/self-signed
          env:
            - name: KUBERNETES_MODE
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: cert-manager-config
          configMap:
            name: cert-manager-config
        - name: certs-volume
          persistentVolumeClaim:
            claimName: certs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-service
  namespace: cert-manager
spec:
  type: NodePort
  selector:
    app: cert-manager
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31500
    - name: metrics
      port: 19090
      targetPort: 19090
      nodePort: 31590
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pvc
  namespace: cert-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-manager-ingress
  namespace: cert-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cert-manager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cert-manager-service
                port:
                  number: 5000