apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-cert-automation
  namespace: docker-k8s-cert-automation
  labels:
    app: docker-k8s-cert-automation
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 31500
  - name: metrics
    port: 19090
    targetPort: 19090
    nodePort: 31590
  selector:
    app: docker-k8s-cert-automation
